GET http://localhost:5000/api/blogs

###

POST http://localhost:5000/api/blogs

content-type: application/json

{
  "text": "derp"
}



###

PUT http://localhost:5000/api/blogs/123




###

DELETE http://localhost:5000/api/blogs/123